# Page settings
baseURL = "https://pisacoderdojo.github.io/"
languageCode = "it-IT"
title = "Pisa Coderdojo"
theme = "minimal"
# googleAnalytics = "UA-XXXXXXX-Y"
content = "ciao"

###
# minimal
###
[params]
    author = "Pisa CoderDojo"
    description = "Sempre in Gamba! Be Cool!"
    githubUsername = "#"
    accent = "#ed2025"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["javascript", "java", "python"]
    profilePic = "banner-medium.jpg"
    css = ["https://fonts.googleapis.com/css?family=Lato&display=swap", "css/mymain.css"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/news/"
    name = "Notizie"
    weight = 3

[[menu.main]]
    url = "/projects/"
    name = "Risorse"
    weight = 4

[[menu.main]]
    url = "/mentors/"
    name = "Mentori"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:pisa.it@coderdojo.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.facebook.com/pisacoderdojo"
    name = "facebook"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/pisacoderdojo/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCnqlpn8ckiVuYbczbQOtPAw"
    name = "youtube"
    weight = 4

[[menu.icon]]
    url = "https://github.com/PisaCoderDojo/"
    name = "github"
    weight = 5


###
# ananke
###
# MetaDataFormat = "yaml"
# DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
# Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
# enableRobotsTXT = true

# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

# [params]
#   favicon = ""
#   description = "The last theme you'll ever need. Maybe."
#   facebook = ""
#   twitter = "https://twitter.com/GoHugoIO"
#   instagram = ""
#   youtube = ""
#   github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#   background_color_class = "bg-black"
#   featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#   recent_posts_number = 2

###
# business-frontpage
###
# [params]
#     author = "CowboySmall"
#     description = "Business Frontpage - A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header"

#     [params.navbar]
#         name = "Pisa CoderDojo"
#         url = "#"

#         [[params.navbar.nav]]
#         current = true
#         name = "Home"
#         url = "#"
#         [[params.navbar.nav]]
#         name = "About"
#         url = "#"
#         [[params.navbar.nav]]
#         name = "Services"
#         url = "#"
#         [[params.navbar.nav]]
#         name = "Contact"
#         url = "/contact"

#     [params.header]
#         name = "Business Name or Tagline"
#         tagline = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non possimus ab labore provident mollitia. Id assumenda voluptate earum corporis facere quibusdam quisquam iste ipsa cumque unde nisi, totam quas ipsam."

#     [params.summary]
#         url = "#"

#         [params.summary.description]

#         [[params.summary.description.items]]
#         description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!"
#         [[params.summary.description.items]]
#         description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum."

#         [params.summary.contact]
#         name = "Start Bootstrap"
#         address1 = "3481 Melrose Place"
#         address2 = "Beverly Hills, CA 90210"
#         phone = "(123) 456-7890"
#         email = "name@example.com"

#     [params.footer]
#         copyright = "Your Website"
